export const EMOJI_CATEGORIES = [
    {
        label: 'Faces',
        icon: '😊',
        emojis: [
            { char: '😊', keywords: 'smile happy face joy' },
            { char: '😂', keywords: 'laugh lol haha tears joy' },
            { char: '🤣', keywords: 'rofl laugh lol' },
            { char: '❤️', keywords: 'heart love red' },
            { char: '😍', keywords: 'heart eyes love' },
            { char: '😒', keywords: 'unamused meh bored' },
            { char: '😭', keywords: 'cry sob sad' },
            { char: '😘', keywords: 'kiss love' },
            { char: '😩', keywords: 'weary tired' },
            { char: '😔', keywords: 'sad pensive' },
            { char: '😏', keywords: 'smirk' },
            { char: '😁', keywords: 'grin happy' },
            { char: '🕶️', keywords: 'sunglasses cool' },
            { char: '😉', keywords: 'wink' },
            { char: '🙄', keywords: 'eye roll' },
            { char: '🤔', keywords: 'think' },
            { char: '😴', keywords: 'sleep' },
            { char: '😷', keywords: 'mask sick' },
            { char: '🤤', keywords: 'drool' },
            { char: '🤢', keywords: 'nauseated sick' },
            { char: '🤩', keywords: 'star eyes' },
            { char: '🥳', keywords: 'party' },
            { char: '🥺', keywords: 'pleading puss eyes' },
            { char: '🥱', keywords: 'yawn' },
            { char: '🤡', keywords: 'clown' }
        ]
    },
    {
        label: 'Gestures',
        icon: '👍',
        emojis: [
            { char: '👍', keywords: 'thumbs up ok' },
            { char: '👎', keywords: 'thumbs down no' },
            { char: '👌', keywords: 'ok hand' },
            { char: '✌️', keywords: 'victory peace' },
            { char: '🤞', keywords: 'fingers crossed' },
            { char: '🤙', keywords: 'call me' },
            { char: '🖐️', keywords: 'hand' },
            { char: '👊', keywords: 'fist' },
            { char: '👋', keywords: 'wave hi hello' },
            { char: '👏', keywords: 'clap' },
            { char: '🙏', keywords: 'pray please thanks' },
            { char: '🙌', keywords: 'hooray hands' },
            { char: '💪', keywords: 'flex strong muscle' },
            { char: '🤝', keywords: 'handshake deal' },
            { char: '🖖', keywords: 'vulcan' },
            { char: '🤘', keywords: 'rock on' }
        ]
    },
    {
        label: 'Animals',
        icon: '🐱',
        emojis: [
            { char: '🐱', keywords: 'cat kitty' },
            { char: '🐶', keywords: 'dog puppy' },
            { char: '🐭', keywords: 'mouse' },
            { char: '🐹', keywords: 'hamster' },
            { char: '🐰', keywords: 'rabbit bunny' },
            { char: '🦊', keywords: 'fox' },
            { char: '🐻', keywords: 'bear' },
            { char: '🐼', keywords: 'panda' },
            { char: '🐨', keywords: 'koala' },
            { char: '🐯', keywords: 'tiger' },
            { char: '🦁', keywords: 'lion' },
            { char: '🐮', keywords: 'cow' },
            { char: '🐷', keywords: 'pig' },
            { char: '🐸', keywords: 'frog' },
            { char: '🐵', keywords: 'monkey' },
            { char: '🐔', keywords: 'chicken' },
            { char: '🐧', keywords: 'penguin' },
            { char: '🐦', keywords: 'bird' },
            { char: '🐤', keywords: 'chick' },
            { char: '🦆', keywords: 'duck' },
            { char: '🦅', keywords: 'eagle' },
            { char: '🦉', keywords: 'owl' },
            { char: '🦇', keywords: 'bat' },
            { char: '🐺', keywords: 'wolf' },
            { char: '🐗', keywords: 'boar' },
            { char: '🐴', keywords: 'horse' },
            { char: '🦄', keywords: 'unicorn' },
            { char: '🐝', keywords: 'bee' },
            { char: '🐛', keywords: 'bug' },
            { char: '🦋', keywords: 'butterfly' },
            { char: '🐌', keywords: 'snail' },
            { char: '🐞', keywords: 'ladybug' },
            { char: '🐜', keywords: 'ant' },
            { char: '🐢', keywords: 'turtle' },
            { char: '🐍', keywords: 'snake' },
            { char: '🦎', keywords: 'lizard' },
            { char: '🦖', keywords: 't-rex' },
            { char: '🦕', keywords: 'dino' },
            { char: '🐙', keywords: 'octopus' },
            { char: '🦑', keywords: 'squid' },
            { char: '🦐', keywords: 'shrimp' },
            { char: '🦞', keywords: 'lobster' },
            { char: '🦀', keywords: 'crab' },
            { char: '🐡', keywords: 'blowfish' },
            { char: '🐠', keywords: 'fish' },
            { char: '🐟', keywords: 'fish' },
            { char: '🐬', keywords: 'dolphin' },
            { char: '🐳', keywords: 'whale' },
            { char: '🐋', keywords: 'whale' },
            { char: '🦈', keywords: 'shark' },
            { char: '🐊', keywords: 'crocodile' },
            { char: '🐅', keywords: 'tiger' },
            { char: '🐆', keywords: 'leopard' },
            { char: '🦓', keywords: 'zebra' },
            { char: '🐘', keywords: 'elephant' },
            { char: '🦏', keywords: 'rhino' },
            { char: '🦛', keywords: 'hippo' },
            { char: '🦒', keywords: 'giraffe' },
            { char: '🐪', keywords: 'camel' },
            { char: '🐫', keywords: 'camel' },
            { char: '🐒', keywords: 'monkey' },
            { char: '🦍', keywords: 'gorilla' },
            { char: '🦧', keywords: 'orangutan' },
            { char: '🐩', keywords: 'poodle' },
            { char: '🐾', keywords: 'paw' }
        ]
    },
    {
        label: 'Food',
        icon: '🍎',
        emojis: [
            { char: '🍎', keywords: 'apple' },
            { char: '🍔', keywords: 'burger fast food' },
            { char: '🍕', keywords: 'pizza' },
            { char: '🍦', keywords: 'ice cream' },
            { char: '🍩', keywords: 'donut' },
            { char: '☕', keywords: 'coffee drink' },
            { char: '🍺', keywords: 'beer' }
        ]
    },
    {
        label: 'Activities',
        icon: '⚽',
        emojis: [
            { char: '⚽', keywords: 'soccer ball' },
            { char: '🏀', keywords: 'basketball' },
            { char: '🏈', keywords: 'football' },
            { char: '🎮', keywords: 'game controller' }
        ]
    }
];
