// Client Intelligence Panel types
// Generated by: client intelligence panel implementation

export interface ActiveProject {
    id: string;
    name: string;
    progress: string;
    percentComplete: number;
    dueDate: string | null;
    editor: string | null;
    accountManager: string | null;
    sizeInGbs: string | null;
    amReview: string;
    tags: string[];
    notes: string | null;
    totalAmount: number | null;
    paid: string | null;
    urgencyScore: number;
}

export interface ClientAlert {
    type: string;
    message: string;
    severity: 'critical' | 'warning' | 'info' | 'success';
}

export interface InboxSignals {
    awaitingOurReply: boolean;
    awaitingTheirReply: boolean;
    clientMentionedPayment: boolean;
    clientAskingAboutDeadline: boolean;
    clientMentionedFiles: boolean;
    clientExpressedFrustration: boolean;
    daysSinceLastReceived: number | null;
    daysSinceLastSent: number | null;
    recentSubjects: string[];
}

export interface TimelineEvent {
    date: string | null;
    label: string;
    type: 'pipeline' | 'email' | 'payment';
    amount?: number;
    isPayment?: boolean;
}

export interface ClientIntelligenceProfile {
    contactId: string;
    name: string;
    email: string;
    company: string | null;
    phone: string | null;
    location: string | null;
    stage: string;
    isClient: boolean;
    contactType: string;
    accountManager: { name: string; email: string } | null;
    leadScore: number;

    tier: 'NEW' | 'STARTER' | 'STANDARD' | 'PREMIUM';

    finance: {
        totalRevenue: number;
        paidRevenue: number;
        unpaidAmount: number;
        totalProjects: number;
        avgProjectValue: number;
        clientSince: string | null;
        hasUnpaid: boolean;
    };

    relationship: {
        health: string;
        daysSinceLastContact: number | null;
        lastMessageDirection: 'SENT' | 'RECEIVED' | null;
        totalEmailsSent: number;
        totalEmailsReceived: number;
        nextFollowupAt: string | null;
    };

    production: {
        matchMethod: 'EMAIL' | 'NAME' | 'NONE';
        activeProjects: ActiveProject[];
        primaryProject: ActiveProject | null;
    };

    inboxSignals: InboxSignals;

    alerts: ClientAlert[];

    timeline: TimelineEvent[];
}
